import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load the .npz data generated by the preprocessing script

data_path = "./data/labeled_data_P.npz"

data = np.load(data_path)
labels = data['labels']

# Count the number of each label
unique_labels, counts = np.unique(labels, return_counts=True)

# Sort data by count in descending order
label_count_pairs = list(zip(unique_labels, counts))
label_count_pairs.sort(key=lambda x: x[1], reverse=True)

sorted_labels = [pair[0] for pair in label_count_pairs]
sorted_counts = [pair[1] for pair in label_count_pairs]

plt.figure(figsize=(10, 6))


# Draw the bar chart
ax = sns.barplot(x=sorted_labels, y=sorted_counts, palette="coolwarm_r", edgecolor='black')

for i, v in enumerate(sorted_counts):
    ax.text(i, v + (max(sorted_counts) * 0.01), str(v),
            color='black', fontweight='bold', ha='center', fontsize=11)

plt.yscale('log')
plt.ylabel('Number of Sentences (Log Scale)', fontsize=12, fontweight='bold')
plt.xlabel('PICO Entity Categories (Participants)', fontsize=12, fontweight='bold')

plt.title('Distribution of Entity Labels: Severe Class Imbalance', fontsize=16, fontweight='bold', pad=20)

plt.grid(axis='y', linestyle='--', alpha=0.6)

# Save and Display
plt.tight_layout()
plt.savefig('viz_class_imbalance_participants.png', dpi=300)

plt.show()